### ISSUE TITLE
Fuel Storage Restrictions Not Working?

### ISSUE THREAD

**Issue by hudso2012** [Dubwise56/Rimatomics#14]
Hello,
I've got a small RimAtomics facility running currently. I'm attempting to restrict my Fuel Storage Pools to only accept used Nuclear Fuel Rods (storage restriction set to 0-99% Fuel Life) but my colonists keep putting brand new (100% Fuel Life) rods into it. The new (100%) rods have their own designated storage elsewhere. 
I believe that this may not be working as intended. I'd like to confirm if that is the case, and if not, figure out what I'm doing incorrectly.
Thank you in advance for the assistance!
![image](https://user-images.githubusercontent.com/67994519/86879771-4950d500-c0b1-11ea-9719-2bf7978b1849.png)
![image](https://user-images.githubusercontent.com/67994519/86879815-5e2d6880-c0b1-11ea-9a90-a34d3fed02e8.png)

**Comment by Dubwise56** [comment]
sorry i didn't get around to replying to this, the fuel pool is using the custom filter tab that the core uses, but the hauling job doesn't  see the custom filters, so in the next patch i changed the fuel pool to use standard filter ui and added allow new and allow used options with new disabled by default
