### ISSUE TITLE
Radiation PPE

### ISSUE THREAD

**Issue by Heatlevelscritical** [Dubwise56/Rimatomics#17]
Am I just incompetent or are my clothing disposal options not giving me options for radiation suits and masks? I'm trying to get rid of damaged radiation PPE, but the option doesn't appear on my crematoriums or my electric smelters.

**Comment by ttr** [comment]
See waving loom, salvage apparel, you will have hazmat section. Not sure if it's displayed before you research hazmat suits.

You can always place it on ground with some chemfuel and blast it away :)

**Comment by Heatlevelscritical** [comment]
Thank you!
