### ISSUE TITLE
punisher railgun railgun railgun

### ISSUE THREAD

**Issue by jal21** [Dubwise56/Rimatomics#4]
i had an event hapen where i get raided by raiders that are higher then my welth would alow and one of the raiders doped whit it 
![20190819140245_1](https://user-images.githubusercontent.com/16976800/63299884-b2f2a580-c28b-11e9-9760-2928b80c90d3.jpg)

**Comment by Dubwise56** [comment]
someones mod must be doing that, i use the same turret def settings as vanilla turrets, nothing i can do about that
