### ISSUE TITLE
Obelisks/Tesla Coils able to be manually targeted without manned SACS

### ISSUE THREAD

**Issue by Stifling-Bossness** [Dubwise56/Rimatomics#6]
[Video](https://youtu.be/q5RPC-J7VNE)
[Mod List](https://gist.github.com/Stifling-Bossness/0aa082f7357179f757b6684e3ef48e61)

As demonstrated, I'm able to manually target and fire the Obelisk without a manned SACS despite the description of the Obelisk. This behavior also applies to the Tesla Coil, but the Marauder and Punisher do require someone at the helm.

**Comment by Dubwise56** [comment]
fixed in the update
