### ISSUE TITLE
Estimated fuel life doesnt take fuel burn rate into account

### ISSUE THREAD

**Issue by Herigony** [Dubwise56/Rimatomics#8]
Changing the fuel burn rate in mod settings doesn't change the estimated fuel life shown in the reactor console. For instance, if a rod shows an estimated 60 days in the reactor console while fuel burn rate is at 100%, if I chnage the fuel burn rate to 300% it will still say 60 days left, although the rod only ends up lasting 20 days. Reopening the reactor console, reloading the save, and restarting the game do not fix the issue.

**Comment by Dubwise56** [comment]
should be fixed in the update
